# Generated by Django 4.1 on 2022-09-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(default=0, max_length=350, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
